from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from typing import Any, List, Optional

from pydantic import BaseModel, Field

from src.orchestrator.contracts.report import AgentReport, ReviewerVerdict
from src.orchestrator.contracts.task import TaskContract


class IterationRecord(BaseModel):
    """Historical record of an individual iteration loop in the workflow."""

    iteration_index: int = Field(..., ge=1, description="Iteration sequence number (1-based)")
    builder_report: Optional[AgentReport] = Field(default=None, description="Report generated by the Builder")
    reviewer_report: Optional[AgentReport] = Field(default=None, description="Report generated by the Reviewer")
    test_results: dict[str, Any] = Field(default_factory=dict, description="Captured test pass/fail results")
    started_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="Iteration start timestamp",
    )
    completed_at: Optional[str] = Field(default=None, description="Iteration completion timestamp")


class WorkflowContext(BaseModel):
    """Shared mutable execution context and memory passed across orchestration turns."""

    run_id: str = Field(
        default_factory=lambda: f"run_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}",
        description="Unique identifier for this workflow execution run",
    )
    task: TaskContract = Field(..., description="Target task contract being executed")
    iteration_index: int = Field(default=0, ge=0, description="Current iteration index (0 before first loop starts)")
    retry_count: int = Field(default=0, ge=0, description="Number of times reviewer rejected and requested changes")
    history: List[IterationRecord] = Field(
        default_factory=list,
        description="Sequential list of all completed iterations",
    )
    modified_files: List[str] = Field(
        default_factory=list,
        description="Cumulative list of files modified during this run",
    )
    artifacts: dict[str, Any] = Field(
        default_factory=dict,
        description="General run-level artifacts: diffs, logs, coverage",
    )
    last_builder_report: Optional[AgentReport] = Field(default=None, description="Most recent Builder report")
    last_reviewer_report: Optional[AgentReport] = Field(default=None, description="Most recent Reviewer report")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Custom metadata tags")

    def start_new_iteration(self) -> IterationRecord:
        """Advance iteration counter and register a new IterationRecord in history."""
        self.iteration_index += 1
        record = IterationRecord(iteration_index=self.iteration_index)
        self.history.append(record)
        return record

    def record_builder_report(self, report: AgentReport) -> None:
        """Update context with latest Builder report and extract modified files."""
        self.last_builder_report = report
        if self.history and self.history[-1].iteration_index == self.iteration_index:
            self.history[-1].builder_report = report

        # Collect modified files if provided in artifacts
        files = report.artifacts.get("modified_files")
        if isinstance(files, list):
            for f in files:
                if isinstance(f, str) and f not in self.modified_files:
                    self.modified_files.append(f)

    def record_reviewer_report(self, report: AgentReport) -> None:
        """Update context with latest Reviewer report and update retry count on rejection."""
        self.last_reviewer_report = report
        if self.history and self.history[-1].iteration_index == self.iteration_index:
            self.history[-1].reviewer_report = report
            self.history[-1].completed_at = datetime.now(timezone.utc).isoformat()

        if report.reviewer_verdict in (ReviewerVerdict.REJECT, ReviewerVerdict.REQUEST_CHANGES):
            self.retry_count += 1

    def is_iteration_budget_exhausted(self) -> bool:
        """Check if workflow has reached maximum permitted iterations."""
        return self.iteration_index >= self.task.budget.max_iterations

    def is_retry_budget_exhausted(self) -> bool:
        """Check if reviewer rejections have exceeded maximum allowed retries."""
        return self.retry_count > self.task.budget.max_retries

    def to_json(self, indent: int | None = None) -> str:
        """Serialize workflow context to deterministic JSON string."""
        return self.model_dump_json(indent=indent)

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowContext:
        """Deserialize workflow context from JSON string."""
        return cls.model_validate_json(json_str)
